name: Deploy backend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile/Dockerfile.backend
          build-args: |
            MONGO_URL=${{ secrets.DATABASE_URL }}
            PORT=${{ secrets.BACKEND_PORT }}
          push: true
          tags: lavkushwaha01/devops_1st_project_backend:${{ github.sha }}

      - name: Deploy to VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key lav@34.131.95.237 "docker stop user_backend || true && docker rm user_backend || true && docker run --name user_backend -d -p 3000:3000 -e MONGO_URL='${{ secrets.DATABASE_URL }}' -e PORT=3000 lavkushwaha01/devops_1st_project_backend:${{ github.sha }}"
