name: Deploy backend
on:
 push: 
  branches: [main]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: cheak the code
      uses: actions/checkout@v2
    
    - name: Docker login
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push 
      uses: docker/build-push-action@v4
      with:
          context: .
          file: ./Dockerfile/Dockerfile.backend
          build-args: |
            MONGO_URL=${{ secrets.DATABASE_URL }}
            PORT=${{ secrets.BACKEND_PORT }}
          push: true
          tags: lavkushwaha01/devops_1st_project_backend:${{ github.sha }}

    - name: Deploy to VM
      uses: 
